#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

echo " Styling, testing, and building your project before committing..."

# check prettier
npm run check-format || 
{
    echo "Prettier check failed. Please run 'npm run format', add changes, and try to commit again.";
    false;
}

# check eslint
npm run check-lint || 
{
    echo "ESLint check failed. Make the required changes above, add changes, and try to commit again.";
    false;
}

# check tsconfig
npm run check-types || 
{
    echo "Type check failed. Make the required changes above, add changes, and try to commit again.";
    false;
}

# build after checks
npm run build || {
    echo "Build failed. View the errors above."
    false;
}
echo "Successfully commit changes!"